[info]
package = "neofetch"
version = "7.1.0"
description = "A command-line system information tool written in bash 3.2+"
architecture = ["amd64", "aarch64"]
license = "MIT"

[source]
files = ["https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.zip"]
sha256sums = ["e610da6561f17c8161337d0c4115da310be576e8699fa2add64e14eeb3f3dcf1"]
