[info]
package = "neofetch"
version = "7.1.0"
description = "A command-line system information tool written in bash 3.2+"
architecture = ["amd64", "aarch64"]
license = "MIT"

[source]
files = ["https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz"]
sha256sums = ["58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7"]
